// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PioneerOnlineLibrary.Infrastructure;

#nullable disable

namespace PioneerOnlineLibrary.API.Migrations
{
    [DbContext(typeof(PioneerDbContext))]
    [Migration("20230221190839_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PioneerOnlineLibrary.Domain.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PioneerOnlineLibrary.Domain.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("PublicationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 2,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 11,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 12,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 13,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 14,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 15,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        },
                        new
                        {
                            BookId = 16,
                            Author = "Aaron Blabey",
                            BookCategory = "Most Recent",
                            Description = "The Latin cogito, ergo sum, usually translated into English as \"I think, therefore I am\", is the \"first principle\" of René Descartes's philosophy. He originally published it in French as je pense, donc je suis in his 1637 Discourse on the Method, so as to reach a wider audience than Latin would have allowed. It later appeared in Latin in his Principles of Philosophy, and a similar phrase also featured prominently in his Meditations on First Philosophy.",
                            Genre = "Comedy",
                            ISBN = "978-0545912402",
                            ImageURL = "http://res.cloudinary.com/dresodocz/image/upload/jwbgka7d6f9mvzipj9rn",
                            IsAvailable = true,
                            Language = "English",
                            Pages = 100,
                            Price = 19m,
                            PublicationDate = "26-11-2016",
                            Publisher = "Scholastic Press",
                            Title = "The Bad Guys"
                        });
                });

            modelBuilder.Entity("PioneerOnlineLibrary.Domain.Model.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PioneerOnlineLibrary.Domain.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PioneerOnlineLibrary.Domain.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PioneerOnlineLibrary.Domain.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PioneerOnlineLibrary.Domain.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PioneerOnlineLibrary.Domain.Model.Review", b =>
                {
                    b.HasOne("PioneerOnlineLibrary.Domain.Model.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
